### ISSUE TITLE
Version 0.1.1 has broken the cheerio test suite

### ISSUE THREAD

**Issue by MylesBorins** [cheeriojs/dom-serializer#78]
when installed with 0.1.1

```
  599 passing (1s)
  1 pending
  1 failing

  1) cheerio .load should render xml in html() when options.xmlMode = true passed to html():
     Error: expected '<mixedcasetag uppercaseattribute></mixedcasetag>' to equal '<mixedcasetag uppercaseattribute=""></mixedcasetag>'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at Context.<anonymous> (test/cheerio.js:375:29)
```

when installed with 0.1.0 the test suite passes

**Comment by jugglinmike** [comment]
This is an intentional bug fix for https://github.com/cheeriojs/cheerio/issues/702; we (Cheerio's maintainers) neglected to update Cheerio's tests because the fix come through a dependency. We should have a correction for this in a new release candidate shortly--see https://github.com/cheeriojs/cheerio/pull/1291. Sorry for the interruption!
